In [1]:
import numpy as np
import pandas as pd

서울시 자치구 연도별 방범용 CCTV 운영 현황_230630기준.csv <br>
해당 파일 숫자변환 => 구별 합계를 내시오

for col in cctv.columns:  <br>
cctv[col]

In [10]:
cctv = pd.read_csv('data/서울시 자치구 연도별 방범용 CCTV 운영 현황_230630기준.csv', encoding='EUC-KR', index_col=0)
cctv

      구분  2015년  2016년  2017년  2018년  2019년  2020년  2021년  2022년   2023년
1    종로구    935  1,066  1,225  1,322  1,338  1,526   1573   1812   1,808
2     중구    363    565    838  1,174  1,234  1,482   1911   2026   2,026
3    용산구  1,398  1,689  1,831  1,888  1,986  2,131   2321   2531   2,647
4    성동구  1,089  1,328  2,103  2,390  2,697  3,162   3519   3627   3,643
5    광진구    638    657  1,112  1,586  2,233  2,375   3111   3370   3,359
6   동대문구  1,202  1,425  1,535  1,775  1,969  2,142   2471   2592   2,592
7    중랑구    751    898  1,047  1,203  2,250  3,165   3592   3856   3,856
8    성북구  1,035  1,534  1,940  2,542  2,895  3,081   3815   4014   4,129
9    강북구    608    840    841  1,159  1,656  2,337   2960   3184   3,184
10   도봉구    345    443    542    679    835    979   1684   1994   2,120
11   노원구    956  1,268  1,433  1,577  1,763  2,021   2171   2284   2,281
12   은평구  1,719  2,075  2,310  2,669  3,164  3,431   3822   4103   4,103
13  서대문구    952  1,179  1,525  1,764  2,100  2,499   2591   2928   3,006
14   마포구    623    970  1,328  1,703  2,011  2,268   2372   2500   2,500
15   양천구  1,898  2,026  2,367  2,655  2,928  3,136   3393   3627   3,609
16   강서구    801    960  1,164  1,386  1,858  2,346   2637   3151   3,209
17   구로구  1,407  1,719  2,231  2,819  3,074  3,455   3842   4013   4,122
18   금천구    990  1,090  1,181  1,563  1,894  2,247   2276   2498   2,730
19  영등포구    904  1,140  1,429  2,055  2,093  3,250   3508   3896   3,964
20   동작구    961  1,200  1,471  1,690  1,904  2,155   2181   2404   2,402
21   관악구  1,496  2,048  2,611  3,247  3,800  4,071   3390   4029   4,245
22   서초구  1,548  1,785  2,169  2,582  2,938  3,175   3442   3180  3,180
23   강남구  2,319  3,447  4,232  4,834  5,459  5,796   6143   6495   6,495
24   송파구    713    798    913  1,364  2,052  2,372   2520   2805   2,821
25   강동구    670    863  1,134  1,596  1,871  2,475   2720   3086   3,088

In [11]:
cctv.columns[1:]

Index(['2015년', '2016년', '2017년', '2018년', '2019년', '2020년', '2021년', '2022년',
       '2023년'],
      dtype='object')

In [12]:
cctv.dtypes

구분       object
2015년    object
2016년    object
2017년    object
2018년    object
2019년    object
2020년    object
2021년     int64
2022년     int64
2023년    object
dtype: object

In [ ]:
cctv1 = cctv['2015년'][:25].str.replace(',','').astype(int)
cctv1

1      935
2      363
3     1398
4     1089
5      638
6     1202
7      751
8     1035
9      608
10     345
11     956
12    1719
13     952
14     623
15    1898
16     801
17    1407
18     990
19     904
20     961
21    1496
22    1548
23    2319
24     713
25     670
Name: 2015년, dtype: int32

In [ ]:
cctv.values[:25, 1:]

array([['935', '1,066', '1,225', '1,322', '1,338', '1,526', 1573, 1812,
        '1,808'],
       ['363', '565', '838', '1,174', '1,234', '1,482', 1911, 2026,
        '2,026'],
       ['1,398', '1,689', '1,831', '1,888', '1,986', '2,131', 2321, 2531,
        '2,647'],
       ['1,089', '1,328', '2,103', '2,390', '2,697', '3,162', 3519, 3627,
        '3,643'],
       ['638', '657', '1,112', '1,586', '2,233', '2,375', 3111, 3370,
        '3,359'],
       ['1,202', '1,425', '1,535', '1,775', '1,969', '2,142', 2471, 2592,
        '2,592'],
       ['751', '898', '1,047', '1,203', '2,250', '3,165', 3592, 3856,
        '3,856'],
       ['1,035', '1,534', '1,940', '2,542', '2,895', '3,081', 3815, 4014,
        '4,129'],
       ['608', '840', '841', '1,159', '1,656', '2,337', 2960, 3184,
        '3,184'],
       ['345', '443', '542', '679', '835', '979', 1684, 1994, '2,120'],
       ['956', '1,268', '1,433', '1,577', '1,763', '2,021', 2171, 2284,
        '2,281'],
       ['1,719', '2,075', '2,310', '2,669', '3,164', '3,431', 3822, 4103,
        '4,103'],
       ['952', '1,179', '1,525', '1,764', '2,100', '2,499', 2591, 2928,
        '3,006'],
       ['623', '970', '1,328', '1,703', '2,011', '2,268', 2372, 2500,
        '2,500'],
       ['1,898', '2,026', '2,367', '2,655', '2,928', '3,136', 3393, 3627,
        '3,609'],
       ['801', '960', '1,164', '1,386', '1,858', '2,346', 2637, 3151,
        '3,209'],
       ['1,407', '1,719', '2,231', '2,819', '3,074', '3,455', 3842, 4013,
        '4,122'],
       ['990', '1,090', '1,181', '1,563', '1,894', '2,247', 2276, 2498,
        '2,730'],
       ['904', '1,140', '1,429', '2,055', '2,093', '3,250', 3508, 3896,
        '3,964'],
       ['961', '1,200', '1,471', '1,690', '1,904', '2,155', 2181, 2404,
        '2,402'],
       ['1,496', '2,048', '2,611', '3,247', '3,800', '4,071', 3390, 4029,
        '4,245'],
       ['1,548', '1,785', '2,169', '2,582', '2,938', '3,175', 3442, 3180,
        '3,180 '],
       ['2,319', '3,447', '4,232', '4,834', '5,459', '5,796', 6143, 6495,
        '6,495'],
       ['713', '798', '913', '1,364', '2,052', '2,372', 2520, 2805,
        '2,821'],
       ['670', '863', '1,134', '1,596', '1,871', '2,475', 2720, 3086,
        '3,088']], dtype=object)

In [ ]:
cctv['2015년'].apply(lambda x: x.replace(',',''))

1      935
2      363
3     1398
4     1089
5      638
6     1202
7      751
8     1035
9      608
10     345
11     956
12    1719
13     952
14     623
15    1898
16     801
17    1407
18     990
19     904
20     961
21    1496
22    1548
23    2319
24     713
25     670
Name: 2015년, dtype: object

In [13]:
for col in cctv.columns[1:]:                # 종로구를 제외한 value값부터 넣음
    if (cctv[col].dtype) == 'object':       # dtype이 object이면
        cctv[col] = cctv[col].apply(lambda x: int(x.replace(',', '')))      #cctv[칼럼명]을 정수로
    else:                               # object 가 아니면
        cctv[col] = cctv[col]           # 그대로 표시

cctv[col]

1     1808
2     2026
3     2647
4     3643
5     3359
6     2592
7     3856
8     4129
9     3184
10    2120
11    2281
12    4103
13    3006
14    2500
15    3609
16    3209
17    4122
18    2730
19    3964
20    2402
21    4245
22    3180
23    6495
24    2821
25    3088
Name: 2023년, dtype: int64

In [14]:
cctv    # 숫자변환 확인

      구분  2015년  2016년  2017년  2018년  2019년  2020년  2021년  2022년  2023년
1    종로구    935   1066   1225   1322   1338   1526   1573   1812   1808
2     중구    363    565    838   1174   1234   1482   1911   2026   2026
3    용산구   1398   1689   1831   1888   1986   2131   2321   2531   2647
4    성동구   1089   1328   2103   2390   2697   3162   3519   3627   3643
5    광진구    638    657   1112   1586   2233   2375   3111   3370   3359
6   동대문구   1202   1425   1535   1775   1969   2142   2471   2592   2592
7    중랑구    751    898   1047   1203   2250   3165   3592   3856   3856
8    성북구   1035   1534   1940   2542   2895   3081   3815   4014   4129
9    강북구    608    840    841   1159   1656   2337   2960   3184   3184
10   도봉구    345    443    542    679    835    979   1684   1994   2120
11   노원구    956   1268   1433   1577   1763   2021   2171   2284   2281
12   은평구   1719   2075   2310   2669   3164   3431   3822   4103   4103
13  서대문구    952   1179   1525   1764   2100   2499   2591   2928   3006
14   마포구    623    970   1328   1703   2011   2268   2372   2500   2500
15   양천구   1898   2026   2367   2655   2928   3136   3393   3627   3609
16   강서구    801    960   1164   1386   1858   2346   2637   3151   3209
17   구로구   1407   1719   2231   2819   3074   3455   3842   4013   4122
18   금천구    990   1090   1181   1563   1894   2247   2276   2498   2730
19  영등포구    904   1140   1429   2055   2093   3250   3508   3896   3964
20   동작구    961   1200   1471   1690   1904   2155   2181   2404   2402
21   관악구   1496   2048   2611   3247   3800   4071   3390   4029   4245
22   서초구   1548   1785   2169   2582   2938   3175   3442   3180   3180
23   강남구   2319   3447   4232   4834   5459   5796   6143   6495   6495
24   송파구    713    798    913   1364   2052   2372   2520   2805   2821
25   강동구    670    863   1134   1596   1871   2475   2720   3086   3088

In [15]:
cctv.dtypes     # 전체데이터 타입 확인

구분       object
2015년     int64
2016년     int64
2017년     int64
2018년     int64
2019년     int64
2020년     int64
2021년     int64
2022년     int64
2023년     int64
dtype: object

In [16]:
cctv['구별 합계'] = cctv.sum(axis=1)
cctv

C:\Users\human\AppData\Local\Temp\ipykernel_13552\2302271069.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  cctv['구별 합계'] = cctv.sum(axis=1)

      구분  2015년  2016년  2017년  2018년  2019년  2020년  2021년  2022년  2023년  구별 합계
1    종로구    935   1066   1225   1322   1338   1526   1573   1812   1808  12605
2     중구    363    565    838   1174   1234   1482   1911   2026   2026  11619
3    용산구   1398   1689   1831   1888   1986   2131   2321   2531   2647  18422
4    성동구   1089   1328   2103   2390   2697   3162   3519   3627   3643  23558
5    광진구    638    657   1112   1586   2233   2375   3111   3370   3359  18441
6   동대문구   1202   1425   1535   1775   1969   2142   2471   2592   2592  17703
7    중랑구    751    898   1047   1203   2250   3165   3592   3856   3856  20618
8    성북구   1035   1534   1940   2542   2895   3081   3815   4014   4129  24985
9    강북구    608    840    841   1159   1656   2337   2960   3184   3184  16769
10   도봉구    345    443    542    679    835    979   1684   1994   2120   9621
11   노원구    956   1268   1433   1577   1763   2021   2171   2284   2281  15754
12   은평구   1719   2075   2310   2669   3164   3431   3822   4103   4103  27396
13  서대문구    952   1179   1525   1764   2100   2499   2591   2928   3006  18544
14   마포구    623    970   1328   1703   2011   2268   2372   2500   2500  16275
15   양천구   1898   2026   2367   2655   2928   3136   3393   3627   3609  25639
16   강서구    801    960   1164   1386   1858   2346   2637   3151   3209  17512
17   구로구   1407   1719   2231   2819   3074   3455   3842   4013   4122  26682
18   금천구    990   1090   1181   1563   1894   2247   2276   2498   2730  16469
19  영등포구    904   1140   1429   2055   2093   3250   3508   3896   3964  22239
20   동작구    961   1200   1471   1690   1904   2155   2181   2404   2402  16368
21   관악구   1496   2048   2611   3247   3800   4071   3390   4029   4245  28937
22   서초구   1548   1785   2169   2582   2938   3175   3442   3180   3180  23999
23   강남구   2319   3447   4232   4834   5459   5796   6143   6495   6495  45220
24   송파구    713    798    913   1364   2052   2372   2520   2805   2821  16358
25   강동구    670    863   1134   1596   1871   2475   2720   3086   3088  17503

#### 선생님 풀이

In [3]:
cctv = pd.read_csv('data/서울시 자치구 연도별 방범용 CCTV 운영 현황_230630기준.csv', encoding='EUC-KR')
cctv.head(3)

,Unnamed: 0,구분,2015년,2016년,2017년,2018년,2019년,2020년,2021년,2022년,2023년
0,1,종로구,935,"1,066","1,225","1,322","1,338","1,526",1573,1812,"1,808"
1,2,중구,363,565,838,"1,174","1,234","1,482",1911,2026,"2,026"
2,3,용산구,"1,398","1,689","1,831","1,888","1,986","2,131",2321,2531,"2,647"

In [12]:
# 위의 DF를 구분을 index로 주고 싶어 : index_col='구분'
# 앞에 Unnamed: 0 컬럼을 지워주고 싶어 : del cctv['Unnamed: 0']
cctv = pd.read_csv('data/서울시 자치구 연도별 방범용 CCTV 운영 현황_230630기준.csv', encoding='EUC-KR', index_col='구분')
del cctv['Unnamed: 0']
cctv.head(3)

     2015년  2016년  2017년  2018년  2019년  2020년  2021년  2022년  2023년
구분
종로구    935  1,066  1,225  1,322  1,338  1,526   1573   1812  1,808
중구     363    565    838  1,174  1,234  1,482   1911   2026  2,026
용산구  1,398  1,689  1,831  1,888  1,986  2,131   2321   2531  2,647

In [13]:
# 각 연도별 컬럼에, 첫번째 데이터의 타입을 확인하겠다!
for col in cctv.columns:
    print(col, type(cctv[col][0]))

2015년 <class 'str'>
2016년 <class 'str'>
2017년 <class 'str'>
2018년 <class 'str'>
2019년 <class 'str'>
2020년 <class 'str'>
2021년 <class 'numpy.int64'>
2022년 <class 'numpy.int64'>
2023년 <class 'str'>

- 데이터 조작에서 str를 쓸수 있는것.
    - find
    - replace

In [14]:
for col in cctv.columns:
    if col in ['2021년','2022년']:
        continue                    # 2021년, 2022년의 경우, 변형없이 그냥 가고
    cctv[col] = cctv[col].str.replace(',', '').astype(int)

In [15]:
cctv['계'] = cctv.sum(axis=1)
cctv.head()

     2015년  2016년  2017년  2018년  2019년  2020년  2021년  2022년  2023년      계
구분
종로구    935   1066   1225   1322   1338   1526   1573   1812   1808  12605
중구     363    565    838   1174   1234   1482   1911   2026   2026  11619
용산구   1398   1689   1831   1888   1986   2131   2321   2531   2647  18422
성동구   1089   1328   2103   2390   2697   3162   3519   3627   3643  23558
광진구    638    657   1112   1586   2233   2375   3111   3370   3359  18441

In [21]:
# 더 간단한 다른 선생님 풀이방법
cctv = pd.read_csv('data/서울시 자치구 연도별 방범용 CCTV 운영 현황_230630기준.csv', 
                   encoding='EUC-KR', index_col='구분', thousands=',')
del cctv['Unnamed: 0']
cctv.head()

     2015년  2016년  2017년  2018년  2019년  2020년  2021년  2022년  2023년
구분
종로구    935   1066   1225   1322   1338   1526   1573   1812   1808
중구     363    565    838   1174   1234   1482   1911   2026   2026
용산구   1398   1689   1831   1888   1986   2131   2321   2531   2647
성동구   1089   1328   2103   2390   2697   3162   3519   3627   3643
광진구    638    657   1112   1586   2233   2375   3111   3370   3359

In [22]:
cctv['계'] = cctv.sum(axis=1)
cctv.head()

     2015년  2016년  2017년  2018년  2019년  2020년  2021년  2022년  2023년      계
구분
종로구    935   1066   1225   1322   1338   1526   1573   1812   1808  12605
중구     363    565    838   1174   1234   1482   1911   2026   2026  11619
용산구   1398   1689   1831   1888   1986   2131   2321   2531   2647  18422
성동구   1089   1328   2103   2390   2697   3162   3519   3627   3643  23558
광진구    638    657   1112   1586   2233   2375   3111   3370   3359  18441

In [24]:
cctv.index

Index(['종로구', '중구', '용산구', '성동구', '광진구', '동대문구', '중랑구', '성북구', '강북구', '도봉구',
       '노원구', '은평구', '서대문구', '마포구', '양천구', '강서구', '구로구', '금천구', '영등포구', '동작구',
       '관악구', '서초구', '강남구', '송파구', '강동구'],
      dtype='object', name='구분')