### 2.10 서울시 구별 CCTV 현황분석
- 서울시 자치구 연도별 방범용 CCTV 운영현황
- 서울시 주민등록인구(구별) 통계

- 컬럼
    - CCTV댓수: 2015년~ 2022년 계
    - 최근 증가율: (2020 ~ 2022) / 총대수 *100
    - 인구수: 2023 1/4분기 자료
    - 내국인:
    - 외국인:
    - 고령자:
    - 외국인비율:
    - 고령자비율:

- 인덱스
    - 각 구

In [2]:
import numpy as np
import pandas as pd

In [5]:
# CCTV 갯수 : 2015년 ~ 2022년 계
cctv = pd.read_csv('data/서울시 자치구 연도별 방범용 CCTV 운영 현황_230630기준.csv', 
            encoding='EUC-KR', index_col='구분', thousands=',')
del cctv['Unnamed: 0']
del cctv['2023년']
cctv['2015년~2022년 계'] = cctv.sum(axis=1)

In [9]:
cctv

      2015년  2016년  2017년  2018년  2019년  2020년  2021년  2022년  2015년~2022년 계
구분
종로구     935   1066   1225   1322   1338   1526   1573   1812          10797
중구      363    565    838   1174   1234   1482   1911   2026           9593
용산구    1398   1689   1831   1888   1986   2131   2321   2531          15775
성동구    1089   1328   2103   2390   2697   3162   3519   3627          19915
광진구     638    657   1112   1586   2233   2375   3111   3370          15082
동대문구   1202   1425   1535   1775   1969   2142   2471   2592          15111
중랑구     751    898   1047   1203   2250   3165   3592   3856          16762
성북구    1035   1534   1940   2542   2895   3081   3815   4014          20856
강북구     608    840    841   1159   1656   2337   2960   3184          13585
도봉구     345    443    542    679    835    979   1684   1994           7501
노원구     956   1268   1433   1577   1763   2021   2171   2284          13473
은평구    1719   2075   2310   2669   3164   3431   3822   4103          23293
서대문구    952   1179   1525   1764   2100   2499   2591   2928          15538
마포구     623    970   1328   1703   2011   2268   2372   2500          13775
양천구    1898   2026   2367   2655   2928   3136   3393   3627          22030
강서구     801    960   1164   1386   1858   2346   2637   3151          14303
구로구    1407   1719   2231   2819   3074   3455   3842   4013          22560
금천구     990   1090   1181   1563   1894   2247   2276   2498          13739
영등포구    904   1140   1429   2055   2093   3250   3508   3896          18275
동작구     961   1200   1471   1690   1904   2155   2181   2404          13966
관악구    1496   2048   2611   3247   3800   4071   3390   4029          24692
서초구    1548   1785   2169   2582   2938   3175   3442   3180          20819
강남구    2319   3447   4232   4834   5459   5796   6143   6495          38725
송파구     713    798    913   1364   2052   2372   2520   2805          13537
강동구     670    863   1134   1596   1871   2475   2720   3086          14415

In [56]:
cctv1 = cctv[['2015년~2022년 계']]
cctv1.values

array([[10797],
       [ 9593],
       [15775],
       [19915],
       [15082],
       [15111],
       [16762],
       [20856],
       [13585],
       [ 7501],
       [13473],
       [23293],
       [15538],
       [13775],
       [22030],
       [14303],
       [22560],
       [13739],
       [18275],
       [13966],
       [24692],
       [20819],
       [38725],
       [13537],
       [14415]], dtype=int64)

In [57]:
cctv2 = cctv[['2020년', '2021년', '2022년']]

cctv2['2020년']

구분
종로구     1526
중구      1482
용산구     2131
성동구     3162
광진구     2375
동대문구    2142
중랑구     3165
성북구     3081
강북구     2337
도봉구      979
노원구     2021
은평구     3431
서대문구    2499
마포구     2268
양천구     3136
강서구     2346
구로구     3455
금천구     2247
영등포구    3250
동작구     2155
관악구     4071
서초구     3175
강남구     5796
송파구     2372
강동구     2475
Name: 2020년, dtype: int64

In [61]:
cctv1 = cctv[['2015년~2022년 계']]
cctv2 = cctv[['2020년', '2021년', '2022년']]

for c2 in cctv2.columns:
    for c1 in cctv1.values:
       c4 = cctv[c2].values / c1*100
c4.round(2)

array([12.57, 14.05, 17.56, 25.16, 23.38, 17.98, 26.75, 27.85, 22.09,
       13.83, 15.84, 28.46, 20.31, 17.34, 25.16, 21.86, 27.84, 17.33,
       27.03, 16.68, 27.95, 22.06, 45.06, 19.46, 21.41])

## 선생님 풀이
### 1. CCTV데이터

In [64]:
# CCTV 갯수 : 2015년 ~ 2022년 계
cctv = pd.read_csv('data/서울시 자치구 연도별 방범용 CCTV 운영 현황_230630기준.csv', 
            encoding='EUC-KR', index_col='구분', thousands=',')

cctv.head(3)

     Unnamed: 0  2015년  2016년  2017년  2018년  2019년  2020년  2021년  2022년  2023년
구분
종로구           1    935   1066   1225   1322   1338   1526   1573   1812   1808
중구            2    363    565    838   1174   1234   1482   1911   2026   2026
용산구           3   1398   1689   1831   1888   1986   2131   2321   2531   2647

In [65]:
cctv.drop(columns=['Unnamed: 0', '2023년'], inplace=True)
cctv.head(3)

     2015년  2016년  2017년  2018년  2019년  2020년  2021년  2022년
구분
종로구    935   1066   1225   1322   1338   1526   1573   1812
중구     363    565    838   1174   1234   1482   1911   2026
용산구   1398   1689   1831   1888   1986   2131   2321   2531

In [66]:
cctv['CCTV댓수'] = cctv.sum(axis=1)
cctv.head(3)

     2015년  2016년  2017년  2018년  2019년  2020년  2021년  2022년  CCTV댓수
구분
종로구    935   1066   1225   1322   1338   1526   1573   1812   10797
중구     363    565    838   1174   1234   1482   1911   2026    9593
용산구   1398   1689   1831   1888   1986   2131   2321   2531   15775

In [67]:
cctv['최근증가율'] = ((cctv['2020년']+ cctv['2021년'] + cctv['2022년']) / cctv['CCTV댓수'] * 100).round(2)
cctv.head(3)

     2015년  2016년  2017년  2018년  2019년  2020년  2021년  2022년  CCTV댓수  최근증가율
구분
종로구    935   1066   1225   1322   1338   1526   1573   1812   10797  45.48
중구     363    565    838   1174   1234   1482   1911   2026    9593  56.49
용산구   1398   1689   1831   1888   1986   2131   2321   2531   15775  44.27

In [68]:
## 위의 방법을 슬라이싱방식으로 
cctv['최근증가율'] = (cctv.iloc[:, 5:-2].sum(axis=1) / cctv['CCTV댓수'] *100).round(2)
cctv.head(3)

     2015년  2016년  2017년  2018년  2019년  2020년  2021년  2022년  CCTV댓수  최근증가율
구분
종로구    935   1066   1225   1322   1338   1526   1573   1812   10797  45.48
중구     363    565    838   1174   1234   1482   1911   2026    9593  56.49
용산구   1398   1689   1831   1888   1986   2131   2321   2531   15775  44.27

In [69]:
cctv.drop(columns='2015년	2016년	2017년	2018년	2019년	2020년	2021년	2022년'.split(), inplace=True)
cctv.head(3)

     CCTV댓수  최근증가율
구분
종로구   10797  45.48
중구     9593  56.49
용산구   15775  44.27

### 2. 서울시 인구데이터 정리하기

In [152]:
person = pd.read_csv('data/서울시 구별 주민등록인구.csv',
                    thousands=',',  skiprows=1 )
person.drop(columns=['세대당인구 (명)','동별(1)','세대 (세대)','세대 (세대).1','계 (명).1','한국인 (명).1','등록외국인 (명).1','인구밀도'], inplace=True)

person

   동별(2)    계 (명)  한국인 (명)  등록외국인 (명)  65세이상고령자 (명)
0     소계  9668008  9426404     241604       1690961
1    종로구   152212   141060      11152         28265
2     중구   131390   120963      10427         25353
3    용산구   232482   217756      14726         39478
4    성동구   287240   280240       7000         48238
5    광진구   350925   336801      14124         54854
6   동대문구   354884   337574      17310         65154
7    중랑구   389928   385003       4925         76116
8    성북구   441855   430100      11755         78427
9    강북구   296934   292762       4172         67056
10   도봉구   312858   310509       2349         68114
11   노원구   506989   502515       4474         93279
12   은평구   468766   464871       3895         90556
13  서대문구   321966   308437      13529         56785
14   마포구   376542   365570      10972         56582
15   양천구   442345   439219       3126         73522
16   강서구   573711   568287       5424         98659
17   구로구   417983   395183      22800         77259
18   금천구   242467   229307      13160         43772
19  영등포구   398999   376614      22385         66014
20   동작구   390377   380201      10176         68766
21   관악구   502628   487815      14813         83420
22   서초구   408979   404831       4148         63328
23   강남구   537817   532798       5019         83097
24   송파구   663704   658006       5698        105161
25   강동구   464027   459982       4045         79706

In [153]:
person.columns = ['구별', '인구수', '내국인', '외국인','고령자']
person

      구별      인구수      내국인     외국인      고령자
0     소계  9668008  9426404  241604  1690961
1    종로구   152212   141060   11152    28265
2     중구   131390   120963   10427    25353
3    용산구   232482   217756   14726    39478
4    성동구   287240   280240    7000    48238
5    광진구   350925   336801   14124    54854
6   동대문구   354884   337574   17310    65154
7    중랑구   389928   385003    4925    76116
8    성북구   441855   430100   11755    78427
9    강북구   296934   292762    4172    67056
10   도봉구   312858   310509    2349    68114
11   노원구   506989   502515    4474    93279
12   은평구   468766   464871    3895    90556
13  서대문구   321966   308437   13529    56785
14   마포구   376542   365570   10972    56582
15   양천구   442345   439219    3126    73522
16   강서구   573711   568287    5424    98659
17   구로구   417983   395183   22800    77259
18   금천구   242467   229307   13160    43772
19  영등포구   398999   376614   22385    66014
20   동작구   390377   380201   10176    68766
21   관악구   502628   487815   14813    83420
22   서초구   408979   404831    4148    63328
23   강남구   537817   532798    5019    83097
24   송파구   663704   658006    5698   105161
25   강동구   464027   459982    4045    79706

In [154]:
# 첫번째 행 지우기
person.drop([0], inplace=True)
person

      구별     인구수     내국인    외국인     고령자
1    종로구  152212  141060  11152   28265
2     중구  131390  120963  10427   25353
3    용산구  232482  217756  14726   39478
4    성동구  287240  280240   7000   48238
5    광진구  350925  336801  14124   54854
6   동대문구  354884  337574  17310   65154
7    중랑구  389928  385003   4925   76116
8    성북구  441855  430100  11755   78427
9    강북구  296934  292762   4172   67056
10   도봉구  312858  310509   2349   68114
11   노원구  506989  502515   4474   93279
12   은평구  468766  464871   3895   90556
13  서대문구  321966  308437  13529   56785
14   마포구  376542  365570  10972   56582
15   양천구  442345  439219   3126   73522
16   강서구  573711  568287   5424   98659
17   구로구  417983  395183  22800   77259
18   금천구  242467  229307  13160   43772
19  영등포구  398999  376614  22385   66014
20   동작구  390377  380201  10176   68766
21   관악구  502628  487815  14813   83420
22   서초구  408979  404831   4148   63328
23   강남구  537817  532798   5019   83097
24   송파구  663704  658006   5698  105161
25   강동구  464027  459982   4045   79706

In [155]:
# 구별을 인덱스로 만들기
person.set_index('구별', inplace=True)
person

         인구수     내국인    외국인     고령자
구별
종로구   152212  141060  11152   28265
중구    131390  120963  10427   25353
용산구   232482  217756  14726   39478
성동구   287240  280240   7000   48238
광진구   350925  336801  14124   54854
동대문구  354884  337574  17310   65154
중랑구   389928  385003   4925   76116
성북구   441855  430100  11755   78427
강북구   296934  292762   4172   67056
도봉구   312858  310509   2349   68114
노원구   506989  502515   4474   93279
은평구   468766  464871   3895   90556
서대문구  321966  308437  13529   56785
마포구   376542  365570  10972   56582
양천구   442345  439219   3126   73522
강서구   573711  568287   5424   98659
구로구   417983  395183  22800   77259
금천구   242467  229307  13160   43772
영등포구  398999  376614  22385   66014
동작구   390377  380201  10176   68766
관악구   502628  487815  14813   83420
서초구   408979  404831   4148   63328
강남구   537817  532798   5019   83097
송파구   663704  658006   5698  105161
강동구   464027  459982   4045   79706

In [156]:
# 외국인 비율, 고령자 비율
person['외국인 비율'] = (person.외국인/person['인구수']*100).round(2)
person['고령자 비율'] = (person['고령자']/person['인구수']*100).round(2)
person

         인구수     내국인    외국인     고령자  외국인 비율  고령자 비율
구별
종로구   152212  141060  11152   28265    7.33   18.57
중구    131390  120963  10427   25353    7.94   19.30
용산구   232482  217756  14726   39478    6.33   16.98
성동구   287240  280240   7000   48238    2.44   16.79
광진구   350925  336801  14124   54854    4.02   15.63
동대문구  354884  337574  17310   65154    4.88   18.36
중랑구   389928  385003   4925   76116    1.26   19.52
성북구   441855  430100  11755   78427    2.66   17.75
강북구   296934  292762   4172   67056    1.41   22.58
도봉구   312858  310509   2349   68114    0.75   21.77
노원구   506989  502515   4474   93279    0.88   18.40
은평구   468766  464871   3895   90556    0.83   19.32
서대문구  321966  308437  13529   56785    4.20   17.64
마포구   376542  365570  10972   56582    2.91   15.03
양천구   442345  439219   3126   73522    0.71   16.62
강서구   573711  568287   5424   98659    0.95   17.20
구로구   417983  395183  22800   77259    5.45   18.48
금천구   242467  229307  13160   43772    5.43   18.05
영등포구  398999  376614  22385   66014    5.61   16.54
동작구   390377  380201  10176   68766    2.61   17.62
관악구   502628  487815  14813   83420    2.95   16.60
서초구   408979  404831   4148   63328    1.01   15.48
강남구   537817  532798   5019   83097    0.93   15.45
송파구   663704  658006   5698  105161    0.86   15.84
강동구   464027  459982   4045   79706    0.87   17.18

### 3.CCTV 데이터와 POP 데이터 합치기

In [164]:
df = pd.merge(cctv, person, left_index=True, right_index=True)
df

      CCTV댓수  최근증가율     인구수     내국인    외국인     고령자  외국인 비율  고령자 비율
종로구    10797  45.48  152212  141060  11152   28265    7.33   18.57
중구      9593  56.49  131390  120963  10427   25353    7.94   19.30
용산구    15775  44.27  232482  217756  14726   39478    6.33   16.98
성동구    19915  51.76  287240  280240   7000   48238    2.44   16.79
광진구    15082  58.72  350925  336801  14124   54854    4.02   15.63
동대문구   15111  47.68  354884  337574  17310   65154    4.88   18.36
중랑구    16762  63.32  389928  385003   4925   76116    1.26   19.52
성북구    20856  52.31  441855  430100  11755   78427    2.66   17.75
강북구    13585  62.43  296934  292762   4172   67056    1.41   22.58
도봉구     7501  62.09  312858  310509   2349   68114    0.75   21.77
노원구    13473  48.07  506989  502515   4474   93279    0.88   18.40
은평구    23293  48.75  468766  464871   3895   90556    0.83   19.32
서대문구   15538  51.60  321966  308437  13529   56785    4.20   17.64
마포구    13775  51.83  376542  365570  10972   56582    2.91   15.03
양천구    22030  46.10  442345  439219   3126   73522    0.71   16.62
강서구    14303  56.87  573711  568287   5424   98659    0.95   17.20
구로구    22560  50.13  417983  395183  22800   77259    5.45   18.48
금천구    13739  51.10  242467  229307  13160   43772    5.43   18.05
영등포구   18275  58.30  398999  376614  22385   66014    5.61   16.54
동작구    13966  48.26  390377  380201  10176   68766    2.61   17.62
관악구    24692  46.53  502628  487815  14813   83420    2.95   16.60
서초구    20819  47.06  408979  404831   4148   63328    1.01   15.48
강남구    38725  47.60  537817  532798   5019   83097    0.93   15.45
송파구    13537  56.86  663704  658006   5698  105161    0.86   15.84
강동구    14415  57.45  464027  459982   4045   79706    0.87   17.18

In [165]:
df.shape

(25, 8)

In [166]:
df.index.name = '구별'
df

      CCTV댓수  최근증가율     인구수     내국인    외국인     고령자  외국인 비율  고령자 비율
구별
종로구    10797  45.48  152212  141060  11152   28265    7.33   18.57
중구      9593  56.49  131390  120963  10427   25353    7.94   19.30
용산구    15775  44.27  232482  217756  14726   39478    6.33   16.98
성동구    19915  51.76  287240  280240   7000   48238    2.44   16.79
광진구    15082  58.72  350925  336801  14124   54854    4.02   15.63
동대문구   15111  47.68  354884  337574  17310   65154    4.88   18.36
중랑구    16762  63.32  389928  385003   4925   76116    1.26   19.52
성북구    20856  52.31  441855  430100  11755   78427    2.66   17.75
강북구    13585  62.43  296934  292762   4172   67056    1.41   22.58
도봉구     7501  62.09  312858  310509   2349   68114    0.75   21.77
노원구    13473  48.07  506989  502515   4474   93279    0.88   18.40
은평구    23293  48.75  468766  464871   3895   90556    0.83   19.32
서대문구   15538  51.60  321966  308437  13529   56785    4.20   17.64
마포구    13775  51.83  376542  365570  10972   56582    2.91   15.03
양천구    22030  46.10  442345  439219   3126   73522    0.71   16.62
강서구    14303  56.87  573711  568287   5424   98659    0.95   17.20
구로구    22560  50.13  417983  395183  22800   77259    5.45   18.48
금천구    13739  51.10  242467  229307  13160   43772    5.43   18.05
영등포구   18275  58.30  398999  376614  22385   66014    5.61   16.54
동작구    13966  48.26  390377  380201  10176   68766    2.61   17.62
관악구    24692  46.53  502628  487815  14813   83420    2.95   16.60
서초구    20819  47.06  408979  404831   4148   63328    1.01   15.48
강남구    38725  47.60  537817  532798   5019   83097    0.93   15.45
송파구    13537  56.86  663704  658006   5698  105161    0.86   15.84
강동구    14415  57.45  464027  459982   4045   79706    0.87   17.18